CC := gcc
CFLAGS := -Wall -Wextra -Werror -pedantic


todo_api_0: 4-request.c
	$(CC) $(CFLAGS) -o todo_api_0 4-request.c


todo_api_1: 5-queries.c
	$(CC) $(CFLAGS) -o todo_api_1 5-queries.c


todo_api_2: 6-headers.c
	$(CC) $(CFLAGS) -o todo_api_2 6-headers.c


todo_api_3: 7-body_parameters.c
	$(CC) $(CFLAGS) -o todo_api_3 7-body_parameters.c


todo_api_4: 8-create_todo.c
	$(CC) $(CFLAGS) -o todo_api_4 8-create_todo.c


todo_api_5: 9-retrieve_todos.c
	$(CC) $(CFLAGS) -o todo_api_5 9-retrieve_todos.c


clean:
	rm -f todo_api_0 todo_api_1 todo_api_2 todo_api_3 todo_api_4 todo_api_5

.PHONY: clean
